### ISSUE TITLE
'leap.common' distribution ?

### ISSUE THREAD

**Issue by kyrios123** [leapcode/bitmask-dev#10]
Hello,
I did successfully build bitmask 0.10.0 but when I run the client, I have the following error:
```
Traceback (most recent call last):
  File "/usr/bin/bitmask", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'leap.common' distribution was not found and is required by leap.bitmask
```

I had a quick look in the leap repositories, and what has the closest name is [leap_pycommon](https://github.com/leapcode/leap_pycommon). Although according to the description, this is not what I need, I also build & install it but of course it didn't help.
Now I am tempted to build the [leap_platform](https://github.com/leapcode/leap_platform) but according to the description it's for the server part while I would like to build the client side modules.  So before going further, I prefer asking here what I miss.

Thanks and congratulation for your great work ! 😃

**Comment by micah** [comment]
Hello @kyrios123 - the leap_pycommon library does seem to be the one that you need.  Perhaps @kalikaneko can help with some ideas for debugging why the version you installed was not found.

I can say for sure you are not needing the leap_platform to get that to work.

**Comment by meskio** [comment]
Yes, leap_pycommon is what you need. You should not need to install it manually, using leap.common from pypi should work fine for current bitmask-dev master. Checkout the Makefile, as it has different options to build bitmask that should work out of the box.
