### ISSUE TITLE
Undefined symbol "i2d_DHparams_bio" for version 0.10.1

### ISSUE THREAD

**Issue by zhou0** [leapcode/bitmask-dev#12]
bitmask
Traceback (most recent call last):
  File "/usr/local/bin/bitmask", line 11, in <module>
    load_entry_point('leap.bitmask', 'console_scripts', 'bitmask')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10.1/src/leap/bitmask/__init__.py", line 4, in <module>
    from .util import here
  File "/usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10.1/src/leap/bitmask/util.py", line 26, in <module>
    from leap.common.files import which
  File "/usr/local/lib/python2.7/site-packages/leap/common/__init__.py", line 3, in <module>
    from leap.common import certs
  File "/usr/local/lib/python2.7/site-packages/leap/common/certs.py", line 26, in <module>
    from OpenSSL import crypto
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: Undefined symbol "i2d_DHparams_bio"

**Comment by meskio** [comment]
Moved to our issue tracker:
https://0xacab.org/leap/bitmask-dev/issues/9116
