### ISSUE TITLE
Debian package for Testing broken

### ISSUE THREAD

**Issue by andreas-h** [leapcode/bitmask-dev#7]
I want to install Bitmask on my Debian Testing (aka. Buster) system.

    $ cat /etc/apt/sources.list.d/bitmask.list                                                                                                     
    deb http://deb.bitmask.net/debian testing main

Installation works, but then

    $ bitmask                                 
    Traceback (most recent call last):
      File "/usr/bin/bitmask", line 11, in <module>
        load_entry_point('leap.bitmask==0.9.2', 'console_scripts', 'bitmask')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2303, in load
        return self.resolve()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2309, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/lib/python2.7/dist-packages/leap/bitmask/app.py", line 61, in <module>
        from leap.bitmask.backend_app import run_backend
      File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend_app.py", line 28, in <module>
        from leap.bitmask.backend.leapbackend import LeapBackend
      File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/leapbackend.py", line 23, in <module>
        from leap.bitmask.backend import components
      File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/components.py", line 44, in <module>
        from leap.bitmask import pix
      File "/usr/lib/python2.7/dist-packages/leap/bitmask/pix.py", line 28, in <module>
        from leap.mail.mail import Account
      File "/usr/lib/python2.7/dist-packages/leap/mail/mail.py", line 41, in <module>
        from leap.mail.adaptors.soledad import SoledadMailAdaptor
      File "/usr/lib/python2.7/dist-packages/leap/mail/adaptors/soledad.py", line 33, in <module>
        from leap.mail import walk
      File "/usr/lib/python2.7/dist-packages/leap/mail/walk.py", line 20, in <module>
        from cryptography.hazmat.backends.multibackend import MultiBackend
    ImportError: No module named multibackend

**Comment by micah** [comment]
Hello @andreas-h -

We have released a new version of bitmask, it would be very helpful if you could try that to see if it solves your issues. 

There is a new repository path that you need to configure, please have a look at https://dl.bitmask.net for the proper instructions.

**Comment by meskio** [comment]
I belive this is solved in 0.10.1, if not feel free to open an issue in our bug tracker: https://0xacab.org/leap/bitmask-dev/issues
