### ISSUE TITLE
ImportError: No module named PyQt5

### ISSUE THREAD

**Issue by zhou0** [leapcode/bitmask-dev#9]
Traceback (most recent call last):
  File "./venv/bin/bitmask", line 11, in <module>
    load_entry_point('leap.bitmask', 'console_scripts', 'bitmask')()
  File "/usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10rc1/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10rc1/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10rc1/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10rc1/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10rc1/src/leap/bitmask/gui/app.py", line 35, in <module>
    from leap.bitmask.gui import app_rc
  File "/usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10rc1/src/leap/bitmask/gui/app_rc.py", line 9, in <module>
    from PyQt5 import QtCore
  File "/usr/home/lzhou/github.com/leapcode/bitmask-dev/archive/bitmask-dev-0.10rc1/venv/lib/python2.7/site-packages/vext/gatekeeper/__init__.py", line 204, in load_module
    raise ImportError("No module named %s" % modulename)
ImportError: No module named PyQt5

**Comment by kalikaneko** [comment]
do you have the python-pyqt5 package installed system wide?

**Comment by zhou0** [comment]
yes, i installed py27-qt5 package on freebsd.

**Comment by micah** [comment]
Hello,

This probably means that python doesn't know where PyQt5 is located. To check, type 'python' at your command prompt, and then do this:

import sys
print sys.path

What you probably need to do is add the directory that contains the PyQt5 module to your PYTHONPATH environment variable. If you use bash, here's how:
Type the following into your shell, and add it to the end of the file ~/.bashrc

export PYTHONPATH=/path/to/PyQt5/directory:$PYTHONPATH

where /path/to/PyQt5/directory is the path to the folder where the PyQt5 library is located.

Also, can you provide the results of:

1. python -V
2. try to import the PyQt5 by running python and then do:

from PyQt5.QtWidgets import QtGui, QtCore

**Comment by zhou0** [comment]
hi, i have this issue solved by build and install pyqt5 from source. But there are more issues.
